#!/bin/bash
cd `dirname "$0"`/..

# note: for valgrind to work on 32-bit targets, the libc6-dbg:i386
# package must be installed.

set -e

for a in $(ls build); do
    echo "$a:"
    valgrind -q build/$a/test
    echo
done
